/**
 * SVG Components Index
 * Generated by svger-cli
 * 
 * Import individual components:
 * import { ButtonIcon } from './components';
 * 
 * Import all components:
 * import * as Icons from './components';
 * import Icons from './components'; // default export
 */

export { default as ButtonIcon } from './ButtonIcon';
// Export all components
export {
  ButtonIcon,
};

// Re-export for convenience
export default {
  ButtonIcon,
};
