/**
 * SVG Components Index
 * Generated by svger-cli
 * 
 * Import individual components:
 * import { IconHome } from './components';
 * 
 * Import all components:
 * import * as Icons from './components';
 */

export { default as IconHome } from './IconHome';
export { default as IconSettings } from './IconSettings';
