/**
 * SVG Components Index
 * Generated by svger-cli
 * 
 * Import individual components:
 * import { StarIcon } from './components';
 * 
 * Import all components:
 * import * as Icons from './components';
 * import Icons from './components'; // default export
 */

export { default as StarIcon } from './StarIcon';
// Export all components
export {
  StarIcon,
};

// Re-export for convenience
export default {
  StarIcon,
};
