/**
 * SVG Components Index
 * Generated by svger-cli
 * 
 * Import individual components:
 * import { StarIcon } from './components';
 * 
 * Import all components:
 * import * as Icons from './components';
 */

export { default as StarIcon } from './StarIcon';
