/**
 * SVG Components Index
 * Generated by svger-cli
 * 
 * Import individual components:
 * import { IconHome } from './components';
 * 
 * Import all components:
 * import * as Icons from './components';
 * import Icons from './components'; // default export
 */

export { default as IconHome } from './IconHome';
export { default as IconSettings } from './IconSettings';
// Export all components
export {
  IconHome,
  IconSettings,
};

// Re-export for convenience
export default {
  IconHome,
  IconSettings,
};
