/**
 * SVG Components Index
 * Generated by svger-cli
 * 
 * Import individual components:
 * import { Invalid } from './components';
 * 
 * Import all components:
 * import * as Icons from './components';
 * import Icons from './components'; // default export
 */

export { default as Invalid } from './Invalid';
// Export all components
export {
  Invalid,
};

// Re-export for convenience
export default {
  Invalid,
};
