/**
 * SVG Components Index
 * Generated by svger-cli
 * 
 * Import individual components:
 * import { UserProfile } from './components';
 * 
 * Import all components:
 * import * as Icons from './components';
 * import Icons from './components'; // default export
 */

export { default as UserProfile } from './UserProfile';
export { default as CheckCircle } from './CheckCircle';
export { default as HomeIcon } from './HomeIcon';
export { default as SettingsGear } from './SettingsGear';
// Export all components
export {
  UserProfile,
  CheckCircle,
  HomeIcon,
  SettingsGear,
};

// Re-export for convenience
export default {
  UserProfile,
  CheckCircle,
  HomeIcon,
  SettingsGear,
};
