/**
 * SVG Components Index
 * Generated by svger-cli
 * 
 * Import individual components:
 * import { Logo } from './components';
 * 
 * Import all components:
 * import * as Icons from './components';
 */

export { default as Logo } from './Logo';
