/**
 * SVG Components Index
 * Generated by svger-cli
 * 
 * Import individual components:
 * import { CheckMark } from './components';
 * 
 * Import all components:
 * import * as Icons from './components';
 */

export { default as CheckMark } from './CheckMark';
