/**
 * SVG Components Index
 * Generated by svger-cli
 * 
 * Import individual components:
 * import { DashboardIcon } from './components';
 * 
 * Import all components:
 * import * as Icons from './components';
 * import Icons from './components'; // default export
 */

export { default as DashboardIcon } from './DashboardIcon';
export { default as HomeIcon } from './HomeIcon';
export { default as LogoutIcon } from './LogoutIcon';
export { default as SettingsIcon } from './SettingsIcon';
export { default as UserIcon } from './UserIcon';
// Export all components
export {
  DashboardIcon,
  HomeIcon,
  LogoutIcon,
  SettingsIcon,
  UserIcon,
};

// Re-export for convenience
export default {
  DashboardIcon,
  HomeIcon,
  LogoutIcon,
  SettingsIcon,
  UserIcon,
};
