/**
 * SVG Components Index
 * Generated by svger-cli
 * 
 * Import individual components:
 * import { Logo } from './components';
 * 
 * Import all components:
 * import * as Icons from './components';
 * import Icons from './components'; // default export
 */

export { default as Logo } from './Logo';
// Export all components
export {
  Logo,
};

// Re-export for convenience
export default {
  Logo,
};
