/**
 * SVG Components Index
 * Generated by svger-cli
 * 
 * Import individual components:
 * import { Invalid } from './components';
 * 
 * Import all components:
 * import * as Icons from './components';
 */

export { default as Invalid } from './Invalid';
