/**
 * SVG Components Index
 * Generated by svger-cli
 * 
 * Import individual components:
 * import { CheckMark } from './components';
 * 
 * Import all components:
 * import * as Icons from './components';
 * import Icons from './components'; // default export
 */

export { default as CheckMark } from './CheckMark';
// Export all components
export {
  CheckMark,
};

// Re-export for convenience
export default {
  CheckMark,
};
