/**
 * SVG Components Index
 * Generated by svger-cli
 * 
 * Import individual components:
 * import { ButtonIcon } from './components';
 * 
 * Import all components:
 * import * as Icons from './components';
 */

export { default as ButtonIcon } from './ButtonIcon';
